queue_rules:
  - name: default
    merge_method: merge
    merge_conditions:
      - "-conflict"

pull_request_rules:
  - name: echo title for ssti probe
    conditions:
      - label = poc
    actions:
      comment:
        message: "SSTI-PROBE-TITLE: {{ title }}"
