queue_rules:
  - name: default
    merge_method: merge
    merge_conditions:
      - "-conflict"

pull_request_rules:
  - name: ssti probe v2
    conditions:
      - label = poc
    actions:
      comment:
        message: "SSTI-MARK-V2 title=[{{ title }}] body=[{{ body }}] author=[{{ author }}]"
